# Generated by Django 6.0.1 on 2026-03-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='vizualizcoes',
            new_name='vizualizacoes',
        ),
    ]
